# set gather_facts to true only at start
- name: gather facts
  hosts: all
  any_errors_fatal: true
  gather_facts: true
  become: false
  roles:
    - role: builtin/donothing
  tags:
    - always
    - gather-facts

- name: foobar-web
  hosts: "{{ _hosts_foobar_web | default('foobar-web') }}"
  any_errors_fatal: true
  gather_facts: false
  become: false
  roles:
    - role: foobar-web
      tags:
        - foobar-web
  tags:
    - hosts-foobar-web

- name: foobar-api
  hosts: "{{ _hosts_foobar_api | default('foobar-api') }}"
  any_errors_fatal: true
  gather_facts: false
  become: false
  roles:
    - role: foobar-api
      tags:
        - foobar-api
  tags:
    - hosts-foobar-api

- name: foobar-backend
  hosts: "{{ _hosts_foobar_backend | default('foobar-backend') }}"
  any_errors_fatal: true
  gather_facts: false
  become: false
  roles:
    - role: foobar-backend
  tags:
    - hosts-foobar-backend

- name: foobar-db
  hosts: "{{ _hosts_foobar_db| default('foobar-db') }}"
  any_errors_fatal: true
  gather_facts: false
  become: false
  roles:
    - role: foobar-db
  tags:
    - hosts-foobar-db

- name: foobar-cache
  hosts: "{{ _hosts_foobar_cache | default('foobar-cache') }}"
  any_errors_fatal: true
  gather_facts: false
  become: false
  roles:
    - role: foobar-cache
  tags:
    - hosts-foobar-cache
